[[redirects]]
from = '/storybook/*'
to = '/storybook/:splat'
force = true

[[redirects]]
from = '/api/*'
to = '/.netlify/functions/:splat'
status = 200
force = true

[[redirects]]
from = '/*'
to = '/index.html'
status = 200

[[headers]]
for = "/manifest.webmanifest"
[headers.values]
Content-Type = "application/manifest+json"

[build]
command = "yarn run build"
publish = "dist"

[dev]
autoLaunch = false
functionsPort = 8885
